const listData= [
    {
        id: 1,
        name: "Mẫu quần jean cho nữ đang hót, vừa dễ thương vừa cá tính ",
        image: "./image/quan4.jpg",
        sale: 10,
        priceOld: 120000,
        priceNew: 108000,
        quantity: 18,
    },
    {
        id: 2,
        name: "Bộ quần áo nữ nữ dành cho các nàng vào những ngày hè nóng bức",
        image: "./image/boquanao.jpg",
        sale: 10,
        priceOld: 130000,
        priceNew: 117000,
        quantity: 18,
    },
    {
        id: 3,
        name: "Mẫu áo nữ xinh xẻo, các nàng nhanh tay rinh về thôi",
        image: "./image/ao2.jpg",
        sale: 20,
        priceOld: 120000,
        priceNew: 96000,
        quantity: 22,
    },
    {
        id: 4,
        name: "Mẫu quần jean nữ cho thể hiện sự cá tính ",
        image: "./image/quannu.jpg",
        sale: 10,
        priceOld: 120000,
        priceNew: 108000,
        quantity: 20,
    },
    {
        id: 5,
        name: "Mẫu quần jean cho nữ đang hót, vừa dễ thương vừa cá tính ",
        image: "./image/quan4.jpg",
        sale: 10,
        priceOld: 120000,
        priceNew: 108000,
        quantity: 25,
    },
    {
        id: 6,
        name: "Mẫu quần jean cho nữ đang hót, vừa dễ thương vừa cá tính ",
        image: "./image/hh.jpg",
        sale: 10,
        priceOld: 120000,
        priceNew: 108000,
        quantity: 19,
    },
    {
        id: 7,
        name: "Mẫu quần trẻ trung năng động dành cho các bạn nam",
        image: "./image/quan5.jpg",
        sale: 10,
        priceOld: 120000,
        priceNew: 108000,
        quantity: 18,
    },
    {
        id: 8,
        name: "Mẫu quần trẻ trung năng động dành cho các bạn nam",
        image: "./image/quan6.jpg",
        sale: 10,
        priceOld: 120000,
        priceNew: 108000,
        quantity: 30,
    },
    {
        id: 9,
        name: "Mẫu áo nữ cute, các nàng còn chờ j mà k nhanh tay rinh về 1 em",
        image: "./image/ao3.jpg",
        sale: 10,
        priceOld: 120000,
        priceNew: 108000,
        quantity: 40,
    },
    {
        id: 10,
        name: "Mẫu áo đôi đang hót cho các cặp đôi, nhanh tay rinh về tặng ngìu iu nào",
        image: "./image/aodoi.jpg",
        sale: 20,
        priceOld: 130000,
        priceNew: 104000,
        quantity: 35,
    },
    {
        id: 11,
        name: "Aó phông dành cho các bạn nam, có thể thoải mái dù trong trạng thái nào",
        image: "./image/ao5.jpg",
        sale: 10,
        priceOld: 120000,
        priceNew: 108000,
        quantity: 20,
    },
    {
        id: 12,
        name: "Mẫu áo đôi đang hót cho các cặp đôi, nhanh tay rinh về tặng ngìu iu nào ",
        image: "./image/aodoi2.jpg",
        sale: 20,
        priceOld: 130000,
        priceNew: 104000,
        quantity: 28,
    },
]
